# Generated by Django 4.2.10 on 2025-05-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featuredsectiontranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='featuredsectiontranslation',
            name='featured_section',
        ),
        migrations.DeleteModel(
            name='FeaturedSection',
        ),
        migrations.DeleteModel(
            name='FeaturedSectionTranslation',
        ),
    ]
