# Generated by Django 4.2.10 on 2025-05-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_featuredsectiontranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testimonialtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testimonialtranslation',
            name='testimonial',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='TestimonialTranslation',
        ),
    ]
