# Generated by Django 4.2.10 on 2025-05-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_testimonialtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontenttranslation',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepagecontenttranslation',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontenttranslation',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='homepagecontenttranslation',
            name='meta_title',
        ),
    ]
