# Generated by Django 4.2.10 on 2025-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_homepagecontent_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontenttranslation',
            name='language',
            field=models.CharField(choices=[('ka', 'Georgian'), ('ru', 'Russian'), ('en', 'English')], max_length=2),
        ),
    ]
