# Generated by Django 4.2.10 on 2025-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_homepagecontenttranslation_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name', max_length=200),
        ),
    ]
