# Generated by Django 4.2.10 on 2025-05-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_homepagecontent_twitter_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='company_name',
            field=models.CharField(help_text='Company name', max_length=200),
        ),
    ]
