# Generated by Django 4.2.10 on 2025-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_homepagecontent_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecontenttranslation',
            old_name='about_content',
            new_name='middle_section_content',
        ),
        migrations.RenameField(
            model_name='homepagecontenttranslation',
            old_name='about_title',
            new_name='middle_section_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='about_content',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='about_title',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='middle_section_content',
            field=models.TextField(blank=True, help_text='Middle section content in Georgian'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='middle_section_title',
            field=models.CharField(blank=True, help_text='Middle section title in Georgian', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='properties_for_rent_subtitle',
            field=models.TextField(blank=True, help_text='Properties for rent section subtitle in Georgian'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='properties_for_rent_title',
            field=models.CharField(blank=True, help_text='Properties for rent section title in Georgian', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='properties_for_sale_subtitle',
            field=models.TextField(blank=True, help_text='Properties for sale section subtitle in Georgian'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='properties_for_sale_title',
            field=models.CharField(blank=True, help_text='Properties for sale section title in Georgian', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='properties_for_rent_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='properties_for_rent_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='properties_for_sale_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepagecontenttranslation',
            name='properties_for_sale_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
