# Generated by Django 4.2.10 on 2025-05-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_about_content_homepagecontenttranslation_middle_section_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(help_text='Main headline in Georgian', max_length=200)),
                ('hero_image', models.ImageField(help_text='Main banner image', upload_to='homepage/')),
                ('main_subtitle', models.CharField(blank=True, help_text='Main subtitle in Georgian', max_length=200)),
                ('main_title', models.TextField(blank=True, help_text='Main title in Georgian')),
                ('main_content', models.TextField(blank=True, help_text='Main content in Georgian')),
                ('our_services_title', models.CharField(blank=True, help_text='Our services title in Georgian', max_length=200)),
                ('our_services_content', models.TextField(blank=True, help_text='Our services content in Georgian')),
                ('office_location_address', models.CharField(blank=True, help_text='Office location address in Georgian', max_length=200)),
                ('office_coordinates', models.JSONField(blank=True, help_text="Office coordinates in format {'lat': float, 'lng': float}", null=True)),
                ('bottom_section_title', models.CharField(blank=True, help_text='Bottom section title in Georgian', max_length=200)),
                ('bottom_section_content', models.TextField(blank=True, help_text='Bottom section content in Georgian')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
            },
        ),
        migrations.CreateModel(
            name='AboutUsContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ka', 'Georgian'), ('ru', 'Russian'), ('en', 'English')], max_length=2)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('properties_for_sale_title', models.CharField(blank=True, max_length=200)),
                ('properties_for_sale_subtitle', models.TextField(blank=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.aboutuscontent')),
            ],
            options={
                'verbose_name': 'About Us Translation',
                'verbose_name_plural': 'About Us Translations',
                'unique_together': {('about_us', 'language')},
            },
        ),
    ]
