# Generated by Django 4.2.10 on 2025-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_aboutuscontent_aboutuscontenttranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuscontenttranslation',
            old_name='properties_for_sale_subtitle',
            new_name='bottom_section_content',
        ),
        migrations.RenameField(
            model_name='aboutuscontenttranslation',
            old_name='properties_for_sale_title',
            new_name='bottom_section_title',
        ),
        migrations.AddField(
            model_name='aboutuscontenttranslation',
            name='main_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutuscontenttranslation',
            name='main_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutuscontenttranslation',
            name='main_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutuscontenttranslation',
            name='our_services_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutuscontenttranslation',
            name='our_services_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
