# Generated by Django 4.2.10 on 2025-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_properties_for_sale_subtitle_aboutuscontenttranslation_bottom_section_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image', upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='logo_white',
            field=models.ImageField(blank=True, help_text='Logo image in white', upload_to='homepage/'),
        ),
    ]
