# Generated by Django 4.2.10 on 2025-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_homepagecontent_logo_homepagecontent_logo_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='logo',
            field=models.ImageField(help_text='Logo image', upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='logo_white',
            field=models.ImageField(help_text='Logo image in white', upload_to='homepage/'),
        ),
    ]
