# Generated by Django 4.2.10 on 2025-05-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name in Georgian", max_length=200),
                ),
                ("description", models.TextField(help_text="Description in Georgian")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GEL", "Georgian Lari"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("TBILISI", "Tbilisi"),
                            ("BATUMI", "Batumi"),
                            ("KUTAISI", "Kutaisi"),
                            ("RUSTAVI", "Rustavi"),
                            ("GORI", "Gori"),
                            ("ZUGDIDI", "Zugdidi"),
                            ("POTI", "Poti"),
                            ("TELAVI", "Telavi"),
                            ("AKHALTSIKHE", "Akhaltsikhe"),
                            ("BORJOMI", "Borjomi"),
                            ("MTSKHETA", "Mtskheta"),
                            ("SIGNAGI", "Signagi"),
                            ("KOBULETI", "Kobuleti"),
                            ("KHASHURI", "Khashuri"),
                            ("SAMTREDIA", "Samtredia"),
                            ("SENAKI", "Senaki"),
                            ("AKHALKALAKI", "Akhalkalaki"),
                            ("KASPI", "Kaspi"),
                            ("TSKALTUBO", "Tskaltubo"),
                            ("OZURGETI", "Ozurgeti"),
                            ("KVARELI", "Kvareli"),
                            ("CHIATURA", "Chiatura"),
                            ("MARNEULI", "Marneuli"),
                            ("GURJAANI", "Gurjaani"),
                            ("DUSHETI", "Dusheti"),
                            ("LAGODEKHI", "Lagodekhi"),
                            ("SACHKHERE", "Sachkhere"),
                            ("DEDOPLISTSKARO", "Dedoplistskaro"),
                            ("NINOTSMINDA", "Ninotsminda"),
                            ("LANCHKHUTI", "Lanchkhuti"),
                            ("AMBROLAURI", "Ambrolauri"),
                            ("KATSKEBI", "Katskebi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("property_id", models.CharField(max_length=100)),
                (
                    "youtube_url",
                    models.CharField(
                        blank=True,
                        help_text="YouTube video URL for property showcase",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("HOUSE", "House"),
                            ("COMMERCIAL", "Commercial"),
                            ("LAND", "Land"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "deal_type",
                    models.CharField(
                        choices=[("SALE", "For Sale"), ("RENT", "For Rent")],
                        max_length=10,
                    ),
                ),
                ("rooms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Area in square meters",
                        max_digits=8,
                    ),
                ),
                ("floor", models.PositiveIntegerField(blank=True, null=True)),
                ("total_floors", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("RENOVATED", "Renovated"),
                            ("REQUIRES_RENOVATION", "Requires Renovation"),
                            ("UNDER_CONSTRUCTION", "Under Construction"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("has_balcony", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("has_elevator", models.BooleanField(default=False)),
                ("has_furniture", models.BooleanField(default=False)),
                ("has_central_heating", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/%Y/%m/")),
                ("is_main", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="property.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("KA", "Georgian"),
                            ("RU", "Russian"),
                            ("EN", "English"),
                        ],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Translation",
                "verbose_name_plural": "Property Translations",
                "unique_together": {("property", "language")},
            },
        ),
    ]
