# Generated by Django 4.2.10 on 2025-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent_name',
            field=models.CharField(blank=True, help_text='Name of the responsible agent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_phone',
            field=models.CharField(blank=True, help_text='Contact number of the agent', max_length=50, null=True),
        ),
    ]
