# Generated by Django 4.2.10 on 2025-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_agent_name_property_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day')], help_text='Applicable only if deal type is RENT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertytranslation',
            name='language',
            field=models.CharField(choices=[('ka', 'Georgian'), ('ru', 'Russian'), ('en', 'English')], max_length=2),
        ),
    ]
