# Generated by Django 4.2.10 on 2025-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_rent_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rooms',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='total_floors',
            new_name='total_rooms',
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day')], default='month', help_text='Applicable only if deal type is RENT', max_length=10, null=True),
        ),
    ]
