# Generated by Django 4.2.10 on 2025-05-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='multiple_has_choices',
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="List of features that apply to the property (e.g., ['balcony', 'parking', 'elevator'])"),
        ),
    ]
