# Generated by Django 4.2.10 on 2025-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertyfeature_remove_property_multiple_has_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='coordinates',
            field=models.JSONField(blank=True, help_text="Property coordinates in format {'lat': float, 'lng': float}", null=True),
        ),
    ]
