# Generated by Django 4.2.10 on 2025-05-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('TBILISI', 'თბილისი'), ('BATUMI', 'ბათუმი'), ('KUTAISI', 'ქუთაისი'), ('RUSTAVI', 'რუსთავი'), ('GORI', 'გორი'), ('ZUGDIDI', 'ზუგდიდი'), ('POTI', 'ფოტი'), ('TELAVI', 'თელავი'), ('AKHALTSIKHE', 'ახალციხე'), ('BORJOMI', 'ბორჯომი'), ('MTSKHETA', 'მცხეთა'), ('SIGNAGI', 'სიღნაღი'), ('KOBULETI', 'ქობულეთი'), ('KHASHURI', 'ხაშური'), ('SAMTREDIA', 'სამტრედია'), ('SENAKI', 'სენაკი'), ('AKHALKALAKI', 'ახალქალაქი'), ('KASPI', 'კასპი'), ('TSKALTUBO', 'წყალტუბო'), ('OZURGETI', 'ოზურგეთი'), ('KVARELI', 'ყვარელი'), ('CHIATURA', 'ჭიათურა'), ('MARNEULI', 'მარნეული'), ('GURJAANI', 'გურჯანი'), ('DUSHETI', 'დუშეთი'), ('LAGODEKHI', 'ლაგოდეხი'), ('SACHKHERE', 'საჩხერე'), ('DEDOPLISTSKARO', 'დედოფლისწყარო'), ('NINOTSMINDA', 'ნინოწმინდა'), ('LANCHKHUTI', 'ლანჩხუთი'), ('AMBROLAURI', 'ამბროლაური')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='deal_type',
            field=models.CharField(choices=[('SALE', 'იყიდება'), ('RENT', 'ქირავდება')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_type',
            field=models.CharField(choices=[('HIGH', 'მაღალი'), ('LOW', 'დაბალი'), ('MEDIUM', 'საშუალო')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'ბინა'), ('HOUSE', 'სახლი'), ('COMMERCIAL', 'კომერციული'), ('LAND', 'მიწა')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('month', 'თვე'), ('week', 'კვირა'), ('day', 'დღე')], default='month', help_text='Applicable only if deal type is RENT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, choices=[('NEW', 'ახალი'), ('RENOVATED', 'გარემონტებული'), ('REQUIRES_RENOVATION', 'საჭიროებს გარემონტებას'), ('UNDER_CONSTRUCTION', 'მიმდინარე რემონტი')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_uuid', models.CharField(max_length=36)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='property.property')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('property', 'visitor_uuid')},
            },
        ),
    ]
